<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHxXxFna\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHxXxFna/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHxXxFna.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHxXxFna\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHxXxFna\App_KernelDevDebugContainer([
    'container.build_hash' => 'HxXxFna',
    'container.build_id' => '19b5c680',
    'container.build_time' => 1743965261,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHxXxFna');
