<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLjeqKzE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLjeqKzE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLjeqKzE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLjeqKzE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLjeqKzE\App_KernelDevDebugContainer([
    'container.build_hash' => 'LjeqKzE',
    'container.build_id' => '17551eb4',
    'container.build_time' => 1744144056,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLjeqKzE');
